### ISSUE TITLE
Resolving fails with latest pdfjs-dist version

### ISSUE THREAD

**Issue by mwohlan** [unjs/unpdf#14]
### Environment

------------------------------
- Operating System: Linux
- Node Version:     v20.12.2
- Nuxt Version:     -
- CLI Version:      3.12.0
- Nitro Version:    2.9.6
- Package Manager:  npm@10.2.4
- Builder:          -
- User Config:      -
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### Reproduction

I set up a nitro project:

https://github.com/mwohlan/undpdf-issue

### Describe the bug

This seems to lead to an error, when using the latest version of pdfjs-dist
```ts
  await configureUnPDF({
    // Use the official PDF.js build
    pdfjs: () => import('pdfjs-dist'),
  });
```
giving the following error message: Resolving failed. Please check the provided configuration.

It works again when downgrading the pdfjs-dist version to for example 4.0.379

**Comment by johannschopplich** [comment]
Hi there! Thanks for the reproduction.

The issue occurs, because PDF.js uses `Promise.withResolvers` in the latest version, which is only compatible in newer environments (such as Node.js 22+).
Why do you use the `pdfjs-dist` package – are you using it for image extraction? If you don't explicitly use `canvas` features, then you can just use the bundled serverless redistribution, which has a [polyfill includes `Promise.withResolvers`](https://github.com/unjs/unpdf/blob/55d90ff29583d8fd5f10843e779c6fe24975d3bc/src/pdfjs-serverless/index.mjs#L10).

**Comment by johannschopplich** [comment]
I've added a note in the README. If you have any other suggesstions for this issue, feel free to add it here!

**Comment by mwohlan** [comment]
> Hi there! Thanks for the reproduction.
> 
> The issue occurs, because PDF.js uses `Promise.withResolvers` in the latest version, which is only compatible in newer environments (such as Node.js 22+). Why do you use the `pdfjs-dist` package – are you using it for image extraction? If you don't explicitly use `canvas` features, then you can just use the bundled serverless redistribution, which has a [polyfill includes `Promise.withResolvers`](https://github.com/unjs/unpdf/blob/55d90ff29583d8fd5f10843e779c6fe24975d3bc/src/pdfjs-serverless/index.mjs#L10).

I am using the renderPageAsImage function. Thank you for the hint about the node versions and for providing this awesome library.

Have a good day!
